#!/usr/bin/env bash

tput civis

clean() {
    tput cnorm
    exit
}
trap clean EXIT SIGINT SIGTERM SIGQUIT

SPINNER="⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

i=0
while [[ 0 ]]; do 
  read -N 1 -t 0.05 tok 
  [[ $? != 142 ]] && break
  printf "\e[2K${SPINNER:$i:1}\r"
  (( i = ( i + 1 ) % ${#SPINNER} ))
done
{ 
  echo -en "$tok"; 
  cat; 
} | ( [[ -n "$1" ]] && $@ || cat )

clean
