#!/usr/bin/env bash

tput civis

clean() {
    tput cnorm
    exit
}
trap clean EXIT SIGINT SIGTERM SIGQUIT

SPINNER="⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

i=0
while ! read -N 1 -t 0.05 tok ; do
  printf "\e[2K${SPINNER:$i:1}\r"
  (( i = ( i + 1 ) % ${#SPINNER} ))
done

echo -en "$tok"
[[ -n "$1" ]] && $@ || cat
clean
